#!/bin/sh
#
# Script for showing volume OSD
# =============================
#
# Dependencies:
#   - notify-send
#   - amixer
#
# Installation
# ------------
#
# $ wget -O notify-volume https://raw.github.com/lauriro/scripts/master/notify-volume
# $ chmod +x notify-volume
# $ # Test, does it works
# $ ./notify-volume
# $ # Or with multiple cards
# $ ./notify-volume 1
# $ # When it's ok, set it up under PATH
# $ sudo mv notify-volume /usr/bin/notify-volume
#
#
# THE BEER-WARE LICENSE
# =====================
#
# <lauri@rooden.ee> wrote this file. As long as you retain this notice you 
# can do whatever you want with this stuff at your own risk. If we meet some 
# day, and you think this stuff is worth it, you can buy me a beer in return.
# -- Lauri Rooden -- https://github.com/lauriro/scripts
#

val=$((10*$(cat /sys/class/backlight/acpi_video0/actual_brightness)))

set -- zero low medium high
shift $((($val+33)*3/100))

notify-send -i notification-display-brightness-$1 -h int:value:$val -h string:x-canonical-private-synchronous:brightness " "


